workflows:
  my-workflow:
    name: Default WorkFlow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - flutter packages pub get
      - flutter test --coverage
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - developerjamiu@gmail.com
